name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  fishing:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Start Scan
        run: |
          bun install && bun run ./helper/proxyip.ts
      - name: Publish Result
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: '["./*.txt"]'
          default_author: github_actions
          fetch: false
          tag_push: "--force"
          message: "Update proxy list"
